datalist<-list(
  Tstep=12,AUS=AUS,m=years,proj_years=proj_years,stocks=stocks,rstocks=rstocks,AUR=c(2,3),
  AU=AU[stock_indices],SR_unit=SR_unit[stock_indices],M_R0=M_K[stock_indices],tau_R0=tau_K[stock_indices],
  M74_alpha=as.matrix(M74_alpha[,stock_indices]),M74_beta=as.matrix(M74_beta[,stock_indices]),
  mu_Parr=as.matrix(mu_Parr[,stock_indices]),
  tau_Parr=as.matrix(tau_Parr[,stock_indices]),
  Smolt_Rsp=as.matrix(Smolt_Rsp[,stock_indices]),
  mu_SmoltW=as.matrix(mu_SmoltW[,stock_indices]),
  tau_SmoltW=as.matrix(tau_SmoltW[,stock_indices]),
  Er=Er,El=El,Edo=Edo,Edc=Edc,Ectn=Ectn,Ecgn=Ecgn,sealMort=sealMort,
  rel_W=rel_W1,rel_R=rel_R1,rel_Rsp=rel_Rsp1,reportcAdj=reportcAdj,
  muTemp=muTemp,tauTemp=tauTemp,mon_Ec=c(6,2,2,2,2,2),
  mon_Edc=rep(1,times=6),
  mon_E=array(c(1,rep(2,times=5),rep(2,times=6),rep(8,times=6),rep(1,times=6),1,rep(2,times=5),rep(1,times=6)),dim=c(6,6)), 
  avail_r=which(stock_indices %in% avail_r),avail_dc=which(stock_indices %in% avail_dc),
  ureport_r=unrep$coef_r,ureport_c=unrep$coef_c,ureport_o=unrep$coef_o,
  PropCR=cat_ratio[,1],PropCW=cat_ratio[,2],
  SmoltWobs=as.matrix(exp(mu_SmoltW[,stock_indices])),
  SmoltRdata=SmoltRdata,
  mu_sp_alpha=mu_sp_alpha[stock_indices],mu_sp_beta=mu_sp_beta[stock_indices],
  CV_sp_alpha=CV_sp_alpha[stock_indices],CV_sp_beta=CV_sp_beta[stock_indices],
  cr_ObsW=cr_ObsW,cl_ObsW=cl_ObsW,cdo_ObsW=cdo_ObsW,cdc_ObsW=cdc_ObsW,cc_ObsW=cc_ObsW,
  cr_ObsRsp=cr_ObsRsp,cr_ObsR=cr_ObsR,cc_ObsR=cc_ObsR,cl_ObsR=cl_ObsR,cdo_ObsR=cdo_ObsR,
  cdc_ObsR=cdc_ObsR,#ncr_ObsTot=cat_r,
  ncc_ObsTot=cat_c,nco_ObsTot=cat_o,
  ncrW_ObsTot=ncrW_ObsTot+0.001,ncrR_ObsTot=cat_r,
  
  nct_ObsTot=cat_t, #trolling catch
  sd_wr=sd_wr,
  #WpropObs=WpropObs,
  log_WpropObs=log(WpropObs), log_RpropObs=log(1-WpropObs),
  sp_count=as.matrix(sp_count[,stock_indices]),
  N_sp_count=as.matrix(N_sp_count[,stock_indices]),
  MSWprop=as.matrix(MSWprop[,stock_indices]),
  RProp=RProp,TrapTot=TrapTot,CatchR=CatchR,
  NLuleRel=NLuleRel,NLuleRec=NLuleRec,yLule=yLule,
  WGrilse=as.matrix(WGrilse[,stock_indices]),
  WMSW=as.matrix(WMSW[,stock_indices]),
  Grilse_all=as.matrix(Grilse_all[,stock_indices]),
  MSW_all=as.matrix(MSW_all[,stock_indices]),
  alpha_ladder=as.matrix(alpha_ladder[,stock_indices]),
  beta_ladder=as.matrix(beta_ladder[,stock_indices]),
  ladder_count=as.matrix(ladder_count[,stock_indices]),
  #au1_stocks=au1_stocks,au2_stocks=au2_stocks,au3_stocks=au3_stocks,
  #au4_stocks=au4_stocks,
  prop_fem=prop_fem,alpha_migr=alpha_migr,
  beta_migr=beta_migr,smolt_year=smolt_year,e_delay=e_delay,
  rivHR=as.matrix(rivHR[,stock_indices]),
  alpha_rel=alpha_rel,beta_rel=beta_rel,
  au1_stocks=au1_stocks,au2_stocks=au2_stocks,au3_stocks=au3_stocks,au4_stocks=au4_stocks)  

